<?xml version="1.0" encoding="utf-8"?>
<xsl:stylesheet
     xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
     version="1.0">

<!-- This stylesheet is used for generating the SP_MAP environment var
to be sourced by the deploy-daq.sh script.  This is the list of
services which are to be built and put into a .ear file.  This is
really an associative array using ',' to associate pairs.  The first
of each pair is the service archive (.sar file) to create (and the
name of the -service.xml file to use and module from the
cluster-config.xml file).  The second of each pair is the project from
which it is created.  -->

  <!-- Pick up the cluster vars, etc. -->
  <xsl:import href="cluster-vars.xsl" />

  <xsl:output method="text"/>

  <xsl:template match="/icecube">
    <!-- Put a warning in for those who like to hack -->
    <xsl:text># This is an automatically generated file.  Do not edit this file.</xsl:text>
    <xsl:value-of select="$newline"/>
    <xsl:text># Rather, edit the cluster-config.xml file from which this file was generated.</xsl:text>
    <xsl:value-of select="$newline"/>

    <xsl:text>SP_MAP="</xsl:text>

    <xsl:apply-templates select="cluster[@name=$cluster-name]" />

    <xsl:text>"</xsl:text>
    <xsl:value-of select="$newline"/>
  </xsl:template>

  <xsl:template match="cluster[@name=$cluster-name]">
    <xsl:for-each select="location">
      <xsl:call-template name="get-SMpair"/>
    </xsl:for-each>

    <xsl:for-each select="every-location">
      <xsl:call-template name="get-SMpair"/>
    </xsl:for-each>
  </xsl:template>

  <xsl:template name="get-SMpair">
    <xsl:for-each select="module">
      <!-- set a var because I can't figure out the following xpath query without using a var -->
      <xsl:variable name="module-name"><xsl:value-of select="name" /></xsl:variable>
      <xsl:if test="/icecube/module-properties-list/module-properties/name[text()=$module-name]/../type='service'" >
        <xsl:value-of select="name" />
        <xsl:if test="id">
          <xsl:text>_</xsl:text>
          <xsl:value-of select="id" />
        </xsl:if>
        <xsl:text>,</xsl:text>
        <xsl:value-of select="/icecube/module-properties-list/module-properties/name[text()=$module-name]/../project" />
        <xsl:text> \</xsl:text>
        <xsl:value-of select="$newline"/>
      </xsl:if>
    </xsl:for-each>
  </xsl:template>

</xsl:stylesheet>
